apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: aneeshgupta25/kub-data-demo:1
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder              
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume          
          hostPath:
            path: /data
            type: DirectoryOrCreate
